### PR TITLE
delegate existing access check to accessApplied method

### PR DESCRIPTION
**Pull request by AbrarSyed**

### CODE REVIEW

**Comment by md-5** [comment]
Use case? Maybe a boolean arg to accessApplied needs to be added to denote whether it was actually applied/.

**Comment by AbrarSyed** [comment]
I would prefer that that specific boolean check be done on the side of the accessApplied() method. This is currently causing a bug for me where applying ATs that have already been applied earlier using other methods show up as broken.

**Comment by md-5** [comment]
Fair point in that EDIT:
Thanks

**Comment by AbrarSyed** [comment]
If you dont mind, requesting the 1.7.4 please

**Pull request closed without merging**
